from __future__ import annotations
from datetime import datetime, timezone
import streamlit as st
from db.cv_store import load_cv
from db.client import get_client
from modules.encryption import (
    create_encrypted_zip,
    generate_checksum,
    verify_package_checksum,
    decrypt_data,
)
import json


# ── Audit logging ─────────────────────────────────────────────

def _log_export(user_id: str, export_type: str, checksum: str) -> None:
    try:
        get_client().table("export_audit").insert({
            "user_id":       user_id,
            "export_type":   export_type,
            "file_checksum": checksum,
        }).execute()
    except Exception:
        pass


# ── Export formats ────────────────────────────────────────────

def _build_plain_text(cv: dict, email: str) -> str:
    """Render CV as clean plain text."""
    lines: list[str] = []
    p = cv.get("personal", {})

    lines.append(p.get("full_name", "").upper())
    contact_parts = filter(None, [
        p.get("email"), p.get("phone"), p.get("location"), p.get("linkedin")
    ])
    lines.append("  |  ".join(contact_parts))
    lines.append("")

    summary = cv.get("profile_summary", "").strip()
    if summary:
        lines += ["PROFILE", "─" * 60, summary, ""]

    skills = cv.get("skills", [])
    if skills:
        lines += ["SKILLS", "─" * 60, ", ".join(skills), ""]

    experience = cv.get("experience", [])
    if experience:
        lines += ["EXPERIENCE", "─" * 60]
        for exp in experience:
            end = "Present" if exp.get("current") else exp.get("end_date", "")
            lines.append(f"{exp.get('role','—')} | {exp.get('company','—')}")
            lines.append(f"{exp.get('start_date','—')} – {end}")
            if exp.get("description"):
                lines.append(exp["description"])
            for ach in exp.get("achievements", []):
                lines.append(f"  • {ach}")
            lines.append("")

    education = cv.get("education", [])
    if education:
        lines += ["EDUCATION", "─" * 60]
        for edu in education:
            lines.append(f"{edu.get('qualification','—')} — {edu.get('subject','')}")
            lines.append(f"{edu.get('institution','—')}  ({edu.get('start_year','')}–{edu.get('end_year','')})")
            if edu.get("grade"):
                lines.append(f"Grade: {edu['grade']}")
            lines.append("")

    certs = cv.get("certifications", [])
    if certs:
        lines += ["CERTIFICATIONS", "─" * 60]
        for cert in certs:
            lines.append(f"{cert.get('name','—')} — {cert.get('issuer','')} ({cert.get('year','')})")
        lines.append("")

    langs = cv.get("languages", [])
    if langs:
        lines += ["LANGUAGES", "─" * 60, ", ".join(langs)]

    lines += [
        "",
        "─" * 60,
        f"Generated by Career Architect Pro  |  {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}",
    ]
    return "\n".join(lines)


# ── Main render ───────────────────────────────────────────────

def render_export_system(user_id: str, email: str, flags: dict) -> None:
    st.header("Export & Package")
    st.caption(
        "Export your CV in multiple formats. "
        "The encrypted package (.cap) uses AES-128 encryption and can only be "
        "decrypted within Career Architect Pro."
    )

    cv, msg = load_cv(user_id)
    if not cv:
        st.warning("No CV found. Please build and save your CV first.")
        return

    p         = cv.get("personal", {})
    safe_name = (p.get("full_name") or email or "cv").replace(" ", "_").lower()
    today_str = datetime.now().strftime("%Y%m%d")

    st.divider()

    col_txt, col_json, col_cap = st.columns(3)

    # ── Plain text export ─────────────────────────────────────
    with col_txt:
        st.subheader("Plain Text")
        st.caption("Clean, ATS-safe plain text. Best for copy/paste into job portals.")
        if st.button("Generate .txt", key="export_txt"):
            plain = _build_plain_text(cv, email)
            chk   = generate_checksum(plain)
            _log_export(user_id, "plain_text", chk)
            fname = f"{safe_name}_{today_str}.txt"
            st.download_button(
                label       = "Download .txt",
                data        = plain.encode("utf-8"),
                file_name   = fname,
                mime        = "text/plain",
                key         = "dl_txt",
            )

    # ── JSON export ───────────────────────────────────────────
    with col_json:
        st.subheader("Structured JSON")
        st.caption("Full CV data in JSON — useful for re-importing or processing.")
        if st.button("Generate .json", key="export_json"):
            cv_json = json.dumps(cv, indent=2, ensure_ascii=False)
            chk     = generate_checksum(cv_json)
            _log_export(user_id, "json", chk)
            fname   = f"{safe_name}_{today_str}.json"
            st.download_button(
                label     = "Download .json",
                data      = cv_json.encode("utf-8"),
                file_name = fname,
                mime      = "application/json",
                key       = "dl_json",
            )

    # ── Encrypted package ─────────────────────────────────────
    with col_cap:
        st.subheader("Encrypted Package")
        st.caption("AES-encrypted .zip archive. Tamper-evident with SHA-256 integrity check.")
        if st.button("Generate .cap package", key="export_cap"):
            zip_bytes = create_encrypted_zip(cv, user_id, email)
            chk_zip   = generate_checksum(zip_bytes.decode("latin-1") if isinstance(zip_bytes, bytes) else zip_bytes)
            chk       = generate_checksum(json.dumps(cv, indent=2, ensure_ascii=False))
            _log_export(user_id, "encrypted_zip", chk)
            fname = f"{safe_name}_{today_str}.cap.zip"
            st.download_button(
                label     = "Download .cap.zip",
                data      = zip_bytes,
                file_name = fname,
                mime      = "application/zip",
                key       = "dl_cap",
            )

    st.divider()

    # ── Package integrity verification ────────────────────────
    with st.expander("Verify an Existing Package"):
        st.caption(
            "Upload a previously exported JSON file to verify it has not been modified."
        )
        uploaded = st.file_uploader("Upload CV JSON", type=["json"], key="verify_upload")
        if uploaded:
            try:
                uploaded_cv = json.loads(uploaded.read().decode("utf-8"))
                expected_chk = st.text_input(
                    "Enter original SHA-256 checksum (from manifest.json inside the .cap.zip)",
                    key="verify_chk",
                )
                if expected_chk and st.button("Verify Integrity", key="verify_btn"):
                    if verify_package_checksum(uploaded_cv, expected_chk.strip()):
                        st.success("Integrity verified — this file has not been modified.")
                    else:
                        st.error("Integrity check FAILED — this file may have been altered.")
            except Exception as exc:
                st.error(f"Could not parse file: {exc}")

    # ── Export history ────────────────────────────────────────
    with st.expander("My Export History"):
        try:
            result = (
                get_client()
                .table("export_audit")
                .select("export_type, file_checksum, exported_at")
                .eq("user_id", user_id)
                .order("exported_at", desc=True)
                .limit(20)
                .execute()
            )
            audits = result.data or []
        except Exception:
            audits = []

        if not audits:
            st.info("No exports recorded yet.")
        else:
            for a in audits:
                st.markdown(
                    f'<div style="background:#F8FAFC;border:1px solid #E2E8F0;'
                    f'padding:8px 14px;border-radius:4px;margin-bottom:4px;font-size:0.82em;">'
                    f'<strong>{a.get("export_type","—")}</strong> &nbsp;·&nbsp; '
                    f'{(a.get("exported_at") or "")[:16]} &nbsp;·&nbsp; '
                    f'checksum: <code>{(a.get("file_checksum") or "")[:12]}…</code>'
                    f'</div>',
                    unsafe_allow_html=True,
                )
